// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amqckedtaegxdbwhayqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtcWNrZWR0YWVneGRid2hheXFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODIwNTcsImV4cCI6MjA3MzM1ODA1N30.ACgZuoiTzZJPsLpiSJ0R5prfqOTolH4flWgSo_fKVn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});